import Link from 'next/link'
import { ArrowDownRight, ArrowUpRight } from 'lucide-react'
import { Header } from '@/components/Header'
import { OpportunityCard } from '@/components/OpportunityCard'
import { sampleOpportunities } from '@/lib/business/sample-data'

export default function Home() {
  return <main><Header /><section className="hero"><div className="hero-kicker"><span>BEAM INSTITUTE CORPORATION</span><span>BUSINESS DEVELOPMENT DIVISION</span></div><div className="hero-copy"><h1>Work that<br /><em>becomes proof.</em></h1><p>Build a public record of real work—one engagement, institutional seat, and earned endorsement at a time.</p><div className="hero-actions"><Link className="solid-button" href="/opportunities">Browse open work <ArrowDownRight size={17} /></Link><a className="text-link" href="#how">See how it works <ArrowUpRight size={15} /></a></div></div><div className="orbit" aria-hidden="true"><span className="orbit-label top">SKILLS</span><span className="orbit-label right">WORK</span><span className="orbit-label bottom">PROOF</span><span className="orbit-label left">TRUST</span><div className="orbit-core">BEAM<br /><small>BUSINESS</small></div></div><div className="hero-index">01 <span /> LIVE CV → REAL ENGAGEMENTS</div></section>

  <section className="manifesto" id="how"><span className="section-number">02</span><div><p className="eyebrow">ONE BODY OF KNOWLEDGE · TWO WAYS TO TEACH IT</p><h2>The work that keeps an institution healthy is the work that builds a career.</h2></div><p className="manifesto-copy">A small partner task and an entity-level compliance seat belong on the same continuum. Every completed engagement adds portfolio evidence. Every endorsement points back to delivered work. Credibility here has an audit trail.</p></section>

  <section className="opportunities"><div className="section-head"><div><span className="eyebrow">BROWSE BEFORE YOU JOIN</span><h2>Open opportunities</h2></div><Link href="/opportunities">View all opportunities <ArrowUpRight size={16} /></Link></div><div className="op-grid">{sampleOpportunities.map((opportunity) => <OpportunityCard key={opportunity.id} opportunity={opportunity} />)}</div></section>

  <section className="profile-proof" id="participants"><div className="profile-intro"><span className="eyebrow">THE LIVE CV</span><h2>Not a résumé.<br /><em>A record.</em></h2><p>Your profile grows through work that happened here: scoped engagements, concrete deliverables, and endorsements only counterparties can issue after completion.</p><a className="solid-button light" href={`${process.env.NEXT_PUBLIC_BEAM_HOME_URL || 'https://home.beamthinktank.space'}/login?intent=profile`}>Build your profile <ArrowUpRight size={16} /></a></div><div className="profile-card"><div className="avatar">AM</div><div className="profile-name"><h3>Ayo Mensah</h3><span className="status"><i /> OPEN · 12 HRS/WEEK</span></div><p>Grants accounting · nonprofit finance · institutional compliance</p><div className="skill-row"><span>Budget Lead</span><span>2 CFR 200</span><span>Internal Controls</span></div><div className="record"><span>03</span><p><strong>completed engagements</strong> across BEAM Business and Black Diaspora Orchestra</p></div><blockquote>“Ayo turned a tangled award budget into an operating system the whole team could use.”<cite>— Engagement endorsement · July 2026</cite></blockquote></div></section>

  <section className="closing"><span className="eyebrow">THE INSTITUTION NEEDS PEOPLE. PEOPLE NEED PROOF.</span><h2>Fill the seat.<br /><em>Build the history.</em></h2><Link className="solid-button" href="/opportunities">Find your next engagement <ArrowUpRight size={17} /></Link></section><footer className="site-footer"><div className="wordmark">BEAM <span>BUSINESS</span></div><p>One legal entity. Many divisions. Shared institutional capacity.</p><span>© 2026 BEAM Institute Corporation</span></footer></main>
}
